# Generated by Django 3.1.2 on 2020-11-20 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(max_length=512, null=True)),
                ('image', models.FileField(upload_to='drawings')),
                ('type', models.IntegerField(choices=[(1, 'Desenho'), (2, 'Pintura'), (3, 'Escultura'), (4, 'Cerâmica'), (5, 'Digital'), (6, 'Foto')])),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oauth.user')),
            ],
            options={
                'db_table': 'gallery_art',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cover', models.FileField(upload_to='exhibition_cover')),
                ('num_works', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oauth.user')),
            ],
            options={
                'db_table': 'gallery_exhibition',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('area', models.IntegerField(choices=[(1, 'Cor'), (2, 'Tinta'), (3, 'Lápis'), (4, 'Nanquim'), (5, 'Papel'), (6, 'Quadro'), (7, 'Estilo')])),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oauth.user')),
            ],
            options={
                'db_table': 'gallery_tag',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.art')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.exhibition')),
            ],
            options={
                'db_table': 'gallery_exhibition_art',
            },
        ),
        migrations.CreateModel(
            name='ArtTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.art')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.tag')),
            ],
            options={
                'db_table': 'gallery_art_tag',
            },
        ),
    ]
